# Site settings
title: Scottish Government Online Services
email: ossd@scotland.gsi.gov.uk
description: The digital handbook has been created to deliver clear content and help build digital services that will appear on mygov.scot. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottishgovernment.github.io/" # the base hostname & protocol for your site
twitter_username: mygovscot
github_username:  scottishgovernment

# Build settings
markdown: kramdown

# Collections
collections:
  standard:
    output: true
  guidelines:
    output: true
  glossary:
    output: true        