# Site settings
title: Scottish Government Digital
email: OSSD@scotland.gsi.gov.uk
description: > # This website details the standards and guidloines used by the Scottish Government whilst developing the mygiv.scot web site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottishgovernment.github.io/" # the base hostname & protocol for your site
twitter_username: mygovscot
github_username:  scottishgov

# Build settings
markdown: kramdown

# Collections
collections:
  guides:
    output: true
  principles:
    output: true
  glossary:
    output: true        