# Site settings
title: Scottish Government Online Services
email: ossd@scotland.gsi.gov.uk
description: We provide standards & guidelines to help organisations build great digital services.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottishgovernment.github.io/" # the base hostname & protocol for your site
twitter_username: mygovscot
github_username:  scottishgovernment

# Build settings
markdown: kramdown

# Collections
collections:
  standard:
    output: true
  guidelines:
    output: true
  glossary:
    output: true        